###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Set simulated to false if you are using this as a configuration for real hardware.
  # This allows users to switch between mock and real hardware by changing a single parameter with config inheritance.
  # [Required]
  simulated: true

  # If the MoveIt Pro Agent should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: True

  # If the MoveIt Pro Agent should launch the robot state publisher.
  # This should be false if you are launching the robot state publisher as part of drivers.
  # [Optional, default=True]
  launch_robot_state_publisher: True

  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "yumi_config"
      path: "config/moveit/yumi.urdf.xacro"
    srdf:
      package: "yumi_config"
      path: "config/moveit/yumi.srdf"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the UR descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
        # Use "mock", "sim", or "real"
      - hardware_interface: "real"

# Sets ROS global params for launch.
# [Optional]
ros_global_params:
  # Whether or not to use simulated time.
  # [Optional, default=False]
  use_sim_time: False

# Configuration files for MoveIt.
# For more information, refer to https://moveit.picknik.ai/main/doc/how_to_guides/moveit_configuration/moveit_configuration_tutorial.html
# [Required]
moveit_params:
  # Used by the Waypoint Manager to save joint states from this joint group.
  joint_group_name: "whole_body"

  ompl_planning:
    package: "yumi_config"
    path: "config/moveit/ompl_planning.yaml"
  stomp_planning:
    package: "yumi_config"
    path: "config/moveit/stomp_planning.yaml"
  pilz_planning:
    package: "yumi_config"
    path: "config/moveit/pilz_industrial_motion_planner_planning.yaml"
  kinematics:
    package: "yumi_config"
    path: "config/moveit/kinematics.yaml"
  servo:
    package: "yumi_config"
    path: "config/moveit/servo.yaml"
  servo_kinematics:
    package: "yumi_config"
    path: "config/moveit/kinematics.yaml"
  joint_limits:
    package: "yumi_config"
    path: "config/moveit/joint_limits.yaml"
  servo_joint_limits:
    package: "yumi_config"
    path: "config/moveit/joint_limits.yaml"
  pilz_cartesian_limits:
    package: "yumi_config"
    path: "config/moveit/pilz_cartesian_limits.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  config:
    package: "yumi_config"
    path: "config/moveit/ros2_controllers.yaml"
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "servo_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  # [Optional, default=[]]
  controllers_inactive_at_startup:
    - "left_arm_controller"
    - "right_arm_controller"
    - "left_gripper_controller"
    - "right_gripper_controller"
    - "whole_body_controller"
    - "servo_controller"
    - "joint_state_broadcaster"
  # Any controllers here will not be spawned by MoveIt Pro.
  # [Optional, default=[]]
  controllers_not_managed: []
  # Optionally configure remapping rules to let multiple controllers receive commands on the same topic.
  # [Optional, default=[]]
  controller_shared_topics: []

# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core:
      package_name: "yumi_config"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "yumi_config"
    relative_path: "waypoints/waypoints.yaml"
